# Generated by Django 5.2 on 2025-05-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='دانلود فیلم', max_length=255, verbose_name='عنوان سایت')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
            },
        ),
    ]
