# Generated by Django 5.2.1 on 2025-05-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_siteconfiguration_model_using_django_solo'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='copyright_text',
            field=models.TextField(blank=True, null=True, verbose_name='متن کپی رایت'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='instagram_page',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='صفحه اینستاگرام'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تماس'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='telegram_channel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='کانال تلگرام'),
        ),
    ]
