# Generated by Django 5.1.4 on 2024-12-24 12:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_change_on_delete_to_cascade_for_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ افزودن'),
            preserve_default=False,
        ),
    ]
