# Generated by Django 5.2 on 2025-05-01 07:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_add_date_to_link_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='نام کشور')),
            ],
            options={
                'verbose_name': 'کشور',
                'verbose_name_plural': 'کشور',
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی')),
                ('full_name_en', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی انگلیسی')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='movie/images', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'کارگردان',
                'verbose_name_plural': 'کارگردان',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'ژانر',
                'verbose_name_plural': 'ژانر',
            },
        ),
        migrations.RenameModel(
            old_name='Character',
            new_name='Actor',
        ),
        migrations.AlterModelOptions(
            name='actor',
            options={'verbose_name': 'بازیگر', 'verbose_name_plural': 'بازیگر'},
        ),
        migrations.RemoveField(
            model_name='film',
            name='country',
        ),
        migrations.AddField(
            model_name='film',
            name='actors',
            field=models.ManyToManyField(related_name='films', to='movie.actor', verbose_name='بازیگر ها'),
        ),
        migrations.AlterField(
            model_name='film',
            name='year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1700), django.core.validators.MaxValueValidator(2025)], verbose_name='سال تولید(میلادی)'),
        ),
        migrations.AddField(
            model_name='film',
            name='countries',
            field=models.ManyToManyField(related_name='films', to='movie.country', verbose_name='کشور ها'),
        ),
        migrations.AlterField(
            model_name='film',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='films', to='movie.director', verbose_name='کارگردان'),
        ),
        migrations.AddField(
            model_name='film',
            name='genres',
            field=models.ManyToManyField(related_name='films', to='movie.genre', verbose_name='ژانر ها'),
        ),
        migrations.DeleteModel(
            name='CharacterItem',
        ),
    ]
