# Generated by Django 5.2 on 2025-05-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_country_director_genre_rename_character_actor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='actors',
            field=models.ManyToManyField(blank=True, related_name='films', to='movie.actor', verbose_name='بازیگر ها'),
        ),
        migrations.AlterField(
            model_name='film',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='films', to='movie.collection', verbose_name='دسته بندی ها'),
        ),
    ]
