# Generated by Django 5.2 on 2025-05-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_add_related_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='visit_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید'),
        ),
    ]
