# Generated by Django 5.2.1 on 2025-05-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_add_parent_field_to_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='نام')),
            ],
            options={
                'verbose_name': 'زبان',
                'verbose_name_plural': 'زبان',
            },
        ),
    ]
