# Generated by Django 5.2.1 on 2025-05-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_add_language_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='languages',
            field=models.ManyToManyField(related_name='films', to='movie.language', verbose_name='زبان ها'),
        ),
    ]
