# Generated by Django 5.2.1 on 2025-05-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_add_languages_to_film_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='language',
        ),
        migrations.AddField(
            model_name='link',
            name='languages',
            field=models.ManyToManyField(related_name='links', to='movie.language', verbose_name='زبان ها'),
        ),
    ]
